# Generated by Django 2.1.3 on 2018-12-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'activesessions',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeof', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'cpu',
            },
        ),
        migrations.CreateModel(
            name='PGA',
            fields=[
                ('name', models.CharField(max_length=130, primary_key=True, serialize=False)),
                ('memory', models.IntegerField()),
            ],
            options={
                'db_table': 'pga',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('profile', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('common', models.CharField(max_length=4)),
                ('authentication_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='SGA',
            fields=[
                ('pool', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('memory', models.IntegerField()),
            ],
            options={
                'db_table': 'sga',
            },
        ),
        migrations.CreateModel(
            name='SQLQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_fulltext', models.TextField()),
            ],
            options={
                'db_table': 'sql_query',
            },
        ),
        migrations.CreateModel(
            name='Tablespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablespace_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('tablespace_inmb', models.IntegerField()),
                ('freespace_inmb', models.IntegerField()),
                ('autoextensible', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tablespace',
            },
        ),
        migrations.CreateModel(
            name='TablespaceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablespace_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('used', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'tablespace_history',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('account_status', models.CharField(max_length=40)),
                ('expiry_date', models.DateField()),
                ('default_tablespace', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=30)),
                ('created', models.DateField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
